# A human-readable name of the Recipe for listing in UIs.
name: 'Drupal SEO and Analytics'
description: "Recommended modules to make your site SEO-friendly and have analytics installed"
# The type key is similar to the package key in module.info.yml. It
# can be used by the UI to group Drupal recipes. Additionally,
# the type 'Site' means that the Drupal recipe will be listed in
# the installer.
type: 'SEO and Analytics'

install:
  - metatag
  - pathauto
  - redirect
  - simple_sitemap
  - schema_metatag
  - google_tag
  - datalayer
  - datalayer_webform

config:
  actions:
    simple_sitemap.type.default:
      createIfNotExists:
        id: default
        label: Default
        description: ''
        sitemap_generator: default
        url_generators:
          entity_menu_link_content: entity_menu_link_content
          entity: entity
          custom: custom
          arbitrary: arbitrary
    simple_sitemap.sitemap.default:
      createIfNotExists:
        dependencies:
          config:
            - simple_sitemap.type.default
        id: default
        label: default
        description: ''
        type: default
        weight: 0
