# A human-readable name of the Recipe for listing in UIs.
name: 'Drupal SEO'
description: "Recommended modules to make your site SEO-friendly"
# The type key is similar to the package key in module.info.yml. It
# can be used by the UI to group Drupal recipes. Additionally,
# the type 'Site' means that the Drupal recipe will be listed in
# the installer.
type: 'SEO'

install:
  - metatag
  - pathauto
  - redirect
  - simple_sitemap
  - schema_metatag
